openapi: 3.0.3

info:
  title: Account API
  version: 0.0.0

servers:
  - url: https://account.danielhowarad.me/api

paths:
  /test:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: string
