openapi: 3.0.3

info:
  title: Internal API
  version: 0.0.0

servers:
  - url: http://sso-backend:80/api

paths:
  /clients/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './common.yaml#/components/schemas/Client'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: './common.yaml#/components/schemas/ErrorWithDetails'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: './common.yaml#/components/schemas/Error'
