openapi: 3.0.3

info:
  title: SSO Internal API
  version: 0.0.0

servers:
  - url: http://sso-internal.danielhowarad.me/api

paths:
  /client/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: './common.yaml#/components/schemas/Client'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: './common.yaml#/components/schemas/Error'
