openapi: 3.0.3

info:
  title: SSO Internal API
  version: 0.0.0

servers:
  - url: https://sso-internal.danielhowarad.me/api

paths:
  /clients:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                    name:
                      type: string
                    showConfirmationPrompt:
                      type: boolean
                    redirects:
                      type: array
                      items:
                        type: string
                        format: uri
