openapi: 3.0.3

info:
  title: SSO API
  version: 0.0.0

servers:
  - url: https://sso.danielhowarad.me/api

paths:
  /admin/clients:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './common.yaml#/components/schemas/Client'
