FROM golang:1.23.1-alpine

WORKDIR /app

RUN apk add nodejs npm
RUN npm install -g nodemon

COPY go.mod go.sum ./
RUN go mod download

CMD ["nodemon", "--signal", "SIGTERM", "--legacy-watch", "--ext", "go", "--watch", "./**/*.*", "--exec", "go run ./cmd/sso-backend"]
