FROM golang:1.23.1-alpine

WORKDIR /app

RUN apk add nodejs npm
RUN npm install -g @redocly/cli@latest
RUN apk add bash

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN bash -c "sh ./make-run-file.sh"
CMD ["bash", "./run.sh"]
