version: '3.8'

services:
  proxy:
    image: nginx:1.25.2
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 80:80
    volumes:
      - ./nginx/proxy_params:/etc/nginx/proxy_params
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  db:
    image: postgres:14.9-alpine
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=sso
      - POSTGRES_PASSWORD=sso
      - POSTGRES_USER=sso
    volumes:
      - /var/lib/postgresql/data
      - ./../backend/sql:/docker-entrypoint-initdb.d
