name: sso-dev

services:
  backend:
    depends_on:
      - db
    build:
      context: ./../backend
      dockerfile: Dockerfile.dev
    environment:
      - PORT=80
      - GIN_MODE=debug
      - PGUSER=sso
      - PGPASSWORD=sso
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=sso
    env_file:
      - path: ./../backend/.env
        required: false
    develop:
      watch:
        - action: sync+restart
          x-initialSync: true
          path: ./../backend
          ignore:
            - ./../backend/go.mod
          target: /app
        - action: rebuild
          x-initialSync: true
          path: ./../backend/go.mod
  proxy:
    depends_on:
      - backend
    image: nginx:1.25.2
    ports:
      - 80:80
    volumes:
      - ./nginx/proxy_params:/etc/nginx/proxy_params
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  db:
    image: postgres:14.9-alpine
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=sso
      - POSTGRES_PASSWORD=sso
      - POSTGRES_USER=sso
    volumes:
      - /var/lib/postgresql/data
      - ./../backend/internal/db/sql:/docker-entrypoint-initdb.d
