//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package enum

import "github.com/go-jet/jet/v2/postgres"

var ProfilePicture = &struct {
	Custom    postgres.StringExpression
	Identicon postgres.StringExpression
	Monsterid postgres.StringExpression
	Wavatar   postgres.StringExpression
	Retro     postgres.StringExpression
	Robohash  postgres.StringExpression
}{
	Custom:    postgres.NewEnumValue("custom"),
	Identicon: postgres.NewEnumValue("identicon"),
	Monsterid: postgres.NewEnumValue("monsterid"),
	Wavatar:   postgres.NewEnumValue("wavatar"),
	Retro:     postgres.NewEnumValue("retro"),
	Robohash:  postgres.NewEnumValue("robohash"),
}
