version: '3.8'

services:
  postgres:
    image: postgres:14.9-alpine
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=sso
      - POSTGRES_PASSWORD=sso
      - POSTGRES_USER=sso
    volumes:
      - /var/lib/postgresql/data
      - ./../sql:/docker-entrypoint-initdb.d
