#!/usr/bin/sh

cd "$(dirname "$0")"

go run github.com/go-jet/jet/v2/cmd/jet -dsn=postgresql://sso:sso@local.danielhoward.me:5432/sso?sslmode=disable -schema=public -path=./.gen
rm -rf ./schema
mkdir -p ./schema
mv ./.gen/sso/public ./schema
rm -rf ./.gen
for file in $$(find ./schema -name '*.go'); do \
	mv "$$file" "$${file%.go}.gen.go"; \
done
